#!/usr/bin/env bash

if [[ "${XDG_SESSION_TYPE}" == wayland ]]
then
  gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
else
  setxkbmap -option ctrl:nocaps
fi

# You can use something similar to the below command to disable the touchpad
# xinput disable 11
