set nocompatible

runtime bundle/vim-pathogen/autoload/pathogen.vim

" remove . from backup directory list
set backupdir-=.
" append new directories to list
set backupdir^=~/.vim/bak

set term=xterm
" Enable 256 colors
set t_Co=256
" configure ansi bg/fg esc sequences
let &t_AB="\e[48;5;%dm"
let &t_AF="\e[38;5;%dm"
" turn syntax highlighting on
syntax on
" my fork of the Tomorrow-Night-Eighties colorscheme
colorscheme tomorrow-night-sxlijin

" set the guifont
if has('gui_running')
    set guifont=Consolas:h9
endif

" from http://dougblack.io/words/a-good-vimrc.html
" enable syntax processing
syntax enable

" simplify entering commands
nnoremap ; :
nnoremap : ;

" avoid using \t in files:
" $ts $tabstop is how many spaces a \t appears as
" $sts $softtabstop is how many spaces are inserted/removed by soft tabbing
" $sw $shiftwidth controls reindent << and >> ops
" $et $expandtab replaces \t in realtime with spaces as inserted
set ts=4 sts=4 sw=4 et

" use file-specific indentation settings in .vim/ftplugin/language.vim
filetype on
filetype plugin on
filetype indent on

set smartindent

" enable line numbering
set number
" highlight current line
set cursorline
" visual autocomplete interface
set wildmenu
" disable vim's automatic redrawing
set lazyredraw

" instant/live search as chars typed in
set incsearch
" highlight matches
set hlsearch

" execute pathogen#infect()
" syntax on
" filetype plugin indent on
call pathogen#infect()
call pathogen#helptags()

" disable scratch/preview in jedi
set completeopt-=preview

" make tab completion go in the forward direction
let g:SuperTabDefaultCompletionType = "<c-n>"
" don't automatically complete text that isn't there
let g:jedi#smart_auto_mappings = 0

" display tabs as special chars
set list
set listchars=tab:→.

" automatic folding
set foldmethod=syntax
set foldnestmax=3
" unfold to deepest level automatically
autocmd Syntax * normal zR

" open sp on bottom, vs on right
set splitbelow
set splitright

" make tabbing more useful
cnoreabbrev <expr> te getcmdtype() == ":" && getcmdline() == 'te' ? 'tabedit' : 'te'
cnoreabbrev <expr> tm getcmdtype() == ":" && getcmdline() == 'tm' ? 'tabmove' : 'tm'
nnoremap tn :tabnext<CR>
nnoremap tp :tabprev<CR>
nnoremap tq :tabclose<CR>
nnoremap t1 1gt
nnoremap t2 2gt
nnoremap t3 3gt
nnoremap t4 4gt
nnoremap t5 5gt
nnoremap t6 6gt
nnoremap t7 7gt
nnoremap t8 8gt
nnoremap t9 9gt
set tabpagemax=100

" enable right-click paste
set mouse=

" auto pastetoggle https://coderwall.com/p/if9mda/
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
