set nocompatible
set term=xterm

" load local config
"if filereadable('~/.vimrc_locals')
"  source ~/.vimrc_locals
"endif

" load plugins
runtime bundle/vim-pathogen/autoload/pathogen.vim
"call pathogen#infect()
"call pathogen#helptags()

" make tab completion go in the forward direction
let g:SuperTabDefaultCompletionType = "<c-n>"

" centralize backups, instead of scattering them
set backupdir-=.
set backupdir^=~/.vim/bak

" color settings
set t_Co=256
let &t_AB="\e[48;5;%dm"
let &t_AF="\e[38;5;%dm"
colorscheme tomorrow-night-sxlijin

" simplify command entry
nnoremap ; :
nnoremap : ;

" assorted usability settings
set number
set cursorline
set wildmenu
set lazyredraw

" improve search visuals
set incsearch
set hlsearch

" highlight whitespace
set list
set listchars=tab:→.,trail:-,extends:>,precedes:<,nbsp:+

" \t settings
" $ts  $tabstop     spaces per tab stop
" $sts $softtabstop spaces inserted/removed by <TAB>/<BS>
" $sw  $shiftwidth  spaces used for builtin indent ops, e.g. <<, >>
" $et  $expandtab   insert spaces until $sts on <TAB>
set ts=2 sts=2 sw=2 et

" syntax magic
syntax on
filetype plugin indent on
set smartindent

" folds
set foldmethod=syntax
set foldnestmax=3
autocmd Syntax * normal zR

" splits
set splitbelow
set splitright

" tabbing
cnoreabbrev te tabedit
cnoreabbrev tm tabmove
nnoremap tk :tabprev<CR>
nnoremap tj :tabnext<CR>
nnoremap tq :tabclose<CR>
nnoremap t1 1gt
nnoremap t2 2gt
nnoremap t3 3gt
nnoremap t4 4gt
nnoremap t5 5gt
nnoremap t6 6gt
nnoremap t7 7gt
nnoremap t8 8gt
nnoremap t9 9gt
set showtabline=2
set tabpagemax=100

" enable right-click paste
" TODO: auto-disable in putty
set mouse=a

" automatic pastetoggle when pasting text
" pastes are preceded by <Esc>[200~ and terminated by <Esc>[201~
imap <Esc>[200~ <C-o>;set paste<CR>
set pastetoggle=<Esc>[201~
