#!/bin/bash

alias t='tmux new-session -A -s default_session'
alias v='vim -p'
alias c='clear'
alias g='git'
alias l='ls -C --classify --color=auto'
alias la='l --almost-all'
alias tl='tree --filelimit 15 -L'
alias t1='tl 1'
alias t2='tl 2'
alias t3='tl 3'
alias t4='tl 4'
alias t5='tl 5'
alias t6='tl 6'
alias t7='tl 7'
alias t8='tl 8'
alias t9='tl 9'
alias gg="git grep --color -rn"
