#!/bin/bash
# ~/.bash_profile: bash(1) personal initialization file, executed for login shells

[ -s ~/.bashrc ] && . ~/.bashrc

# Load RVM into a shell session *as a function*
[ -s "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm" || :
