#!/bin/bash

alias t='tmux new-session -A -s default_session'
alias v='vim -p'
alias c='clear'
alias g='git'
alias k='kubectl'
alias l='ls -F --color=auto'
alias la='l -a'
alias ll='l -l'
alias tl='tree --filelimit 15 -L'
alias t1='tl 1'
alias t2='tl 2'
alias t3='tl 3'
alias t4='tl 4'
alias t5='tl 5'
alias t6='tl 6'
alias t7='tl 7'
alias t8='tl 8'
alias t9='tl 9'

if command -v inotifywait &>/dev/null
then
  function inotifywhile {
      echo ./ INOTIFY-START .
      inotifywait --monitor --recursive \
        --event MODIFY \
        --event CREATE \
        --event DELETE \
        --event MOVE \
        --event ATTRIB \
        ./
  }
else
  function inotifywhile {
    echo ./ INOTIFY-START .
    fswatch .
  }
fi

function debounce_stdin {
  echo "Skipping $(timeout 1 cat | wc -l) events"
}
